### PR TITLE
Upgrade to Selenium 3 and add OSX geckodriver binary

### LINKED ISSUE #14: Support Firefox 48+
Selenium 2.x doesn't support FF 48, and Selenium 3 is not available yet :(

### PR DESCRIPTION
**Pull request by desbo**
This fixes #14. 

It needed a [geckodriver](https://github.com/mozilla/geckodriver) binary, so I've compiled it on my Mac and included it here. This does mean it won't work on other OSes until we do the same for them.

### CODE REVIEW

**Comment by gidsg** [comment]
👍 💥

**Comment by desbo** [comment]
Does anyone have write access to this repository? 😄

**Comment by NataliaLKB** [comment]
Thanks so much for doing this @desbo ! 😄

**Comment by LATaylor-guardian** [comment]
@desbo I've just added you.

**Comment by mchv** [comment]
👍

**Pull request merged**
